import { System } from '@/app/model/System'

export const systems: { [key: string]: System } = {
  austin: {
    id: 'austin',
    metroArea: 'Austin',
    city: 'austin',
    country: 'USA',
    longitude: -97.7431,
    latitude: 30.2672,
  },
  bergen: {
    id: 'bergen',
    metroArea: 'Bergen',
    city: 'bergen',
    country: 'Norway',
    longitude: 5.3221,
    latitude: 60.3913,
  },
  boston: {
    id: 'boston',
    metroArea: 'Boston',
    city: 'boston',
    country: 'USA',
    longitude: -71.0589,
    latitude: 42.3601,
  },
  chattanooga: {
    id: 'chattanooga',
    metroArea: 'Chattanooga',
    city: 'chattanooga',
    country: 'USA',
    longitude: -85.3097,
    latitude: 35.0456,
  },
  chicago: {
    id: 'chicago',
    metroArea: 'Chicago',
    city: 'chicago',
    country: 'USA',
    longitude: -87.6298,
    latitude: 41.8781,
  },
  columbus: {
    id: 'columbus',
    metroArea: 'Columbus',
    city: 'columbus',
    country: 'USA',
    longitude: -82.9988,
    latitude: 39.9612,
  },
  guadalajara: {
    id: 'guadalajara',
    metroArea: 'Guadalajara',
    city: 'guadalajara',
    country: 'Mexico',
    longitude: -103.3496,
    latitude: 20.6597,
  },
  helsinki: {
    id: 'helsinki',
    metroArea: 'Helsinki',
    city: 'helsinki',
    country: 'Finland',
    longitude: 24.9384,
    latitude: 60.1699,
  },
  jersey_city: {
    id: 'jersey_city',
    metroArea: 'Jersey City',
    city: 'jersey_city',
    country: 'USA',
    longitude: -74.0776,
    latitude: 40.7282,
  },
  london: {
    id: 'london',
    metroArea: 'London',
    city: 'london',
    country: 'United Kingdom',
    longitude: -0.1276,
    latitude: 51.5074,
  },
  los_angeles: {
    id: 'los_angeles',
    metroArea: 'Los Angeles',
    city: 'los_angeles',
    country: 'USA',
    longitude: -118.2437,
    latitude: 34.0522,
  },
  mexico_city: {
    id: 'mexico_city',
    metroArea: 'Mexico City',
    city: 'mexico_city',
    country: 'Mexico',
    longitude: -99.1332,
    latitude: 19.4326,
  },
  montreal: {
    id: 'montreal',
    metroArea: 'Montreal',
    city: 'montreal',
    country: 'Canada',
    longitude: -73.5673,
    latitude: 45.5017,
  },
  new_york_city: {
    id: 'nyc',
    metroArea: 'New York City',
    city: 'new_york_city',
    country: 'USA',
    longitude: -74.006,
    latitude: 40.7128,
  },
  oslo: {
    id: 'oslo',
    metroArea: 'Oslo',
    city: 'oslo',
    country: 'Norway',
    longitude: 10.7522,
    latitude: 59.9139,
  },
  philadelphia: {
    id: 'philadelphia',
    metroArea: 'Philadelphia',
    city: 'philadelphia',
    country: 'USA',
    longitude: -75.1652,
    latitude: 39.9526,
  },
  pittsburgh: {
    id: 'pittsburgh',
    metroArea: 'Pittsburgh',
    city: 'pittsburgh',
    country: 'USA',
    longitude: -79.9959,
    latitude: 40.4406,
  },
  rosario: {
    id: 'rosario',
    metroArea: 'Rosario',
    city: 'rosario',
    country: 'Argentina',
    longitude: -60.6393,
    latitude: -32.9587,
  },
  san_francisco: {
    id: 'sf',
    metroArea: 'San Francisco',
    city: 'san_francisco',
    country: 'USA',
    longitude: -122.4194,
    latitude: 37.7749,
  },
  seoul: {
    id: 'seoul',
    metroArea: 'Seoul',
    city: 'seoul',
    country: 'South Korea',
    longitude: 126.978,
    latitude: 37.5665,
  },
  taipei: {
    id: 'taipei',
    metroArea: 'Taipei',
    city: 'taipei',
    country: 'Taiwan',
    longitude: 121.5654,
    latitude: 25.033,
  },
  toronto: {
    id: 'toronto',
    metroArea: 'Toronto',
    city: 'toronto',
    country: 'Canada',
    longitude: -79.3832,
    latitude: 43.6532,
  },
  trondheim: {
    id: 'trondheim',
    metroArea: 'Trondheim',
    city: 'trondheim',
    country: 'Norway',
    longitude: 10.3951,
    latitude: 63.4305,
  },
  vancouver: {
    id: 'vancouver',
    metroArea: 'Vancouver',
    city: 'vancouver',
    country: 'Canada',
    longitude: -123.1216,
    latitude: 49.2827,
  },
  washington_dc: {
    id: 'dc',
    metroArea: 'Washington D.C.',
    city: 'washington_dc',
    country: 'USA',
    longitude: -77.0369,
    latitude: 38.9072,
  },
}

export const ALL_CITIES = Object.values(systems)

export const US_SYSTEMS = ALL_CITIES.filter(
  (system) => system.country === 'USA'
).map((system) => system.id)
