import type { BikerColors } from './colors'
import type { BasketType } from './Basket'
import type { OuterGuard, SkirtGuard } from './Skirt'
import type { DownTubeCurve } from './Frame'

export interface CityBikeConfig {
  colors: Partial<BikerColors>
  basketType: BasketType
  skirtGuard: SkirtGuard
  /** Down-tube sweep profile; defaults to 'default' when omitted. */
  downTube?: DownTubeCurve
}

/** Shared outerGuard on Lyft-built bikes: black rib swept from 3 o'clock to 150°. */
const lyftOuterGuard: OuterGuard = { endDeg: 150, color: '#1a1a1a' }

/**
 * Per-city bike configs, interpreted from real side-on photos of each system's
 * bicycle. See `docs/city-bike-colors.csv` for sources, confidence, and livery
 * notes. Keys match the ids in `constants/cities.ts`.
 *
 * Bike parts only — the rider (shirt/pants/skin/helmet) keeps the defaults.
 * `skirtGuard` is the branded panel over the rear wheel; `basketType` selects
 * the front-carrier shape (shared across cities with similar hardware).
 */
export const CITY_BIKE_CONFIG: Record<string, CityBikeConfig> = {
  austin: {
    basketType: 'rack',
    skirtGuard: {
      type: 'LEVEL_1',
      color: '#6b4fa0',
      outerGuard: lyftOuterGuard,
    },
    colors: {
      frame: '#17a3a0',
      frontFender: '#17a3a0',
      frameDark: '#0f7f7d',
      basket: '#0f7f7d',
      saddle: '#1b1b1b',
      tire: '#1a1a1a',
      wheelRim: '#ece8df',
      spoke: '#c9ccce',
      hub: '#7a7a7a',
      ring: '#2a2a2a',
      crank: '#2a2a2a',
    },
  },
  bergen: {
    basketType: 'rack',
    skirtGuard: {
      type: '9_1_CIRCLE',
      color: '#dcdcd8',
      outerGuard: { endDeg: 180, color: '#3fae2c' },
    },
    downTube: 'nordic',
    colors: {
      frame: '#e8e7e3',
      frontFender: '#3fae2c',
      frameDark: '#3fae2c',
      basket: '#3fae2c',
      saddle: '#d6d6d3',
      tire: '#1a1a1a',
      wheelRim: '#3fae2c',
      spoke: '#c9ccce',
      hub: '#7a7a7a',
      ring: '#2a8a20',
      crank: '#2a2a2a',
    },
  },
  boston: {
    basketType: 'box',
    skirtGuard: {
      type: 'CRESCENT',
      color: '#1c6fb0',
      outerGuard: lyftOuterGuard,
    },
    downTube: 'lyft',
    colors: {
      frame: '#1c8ac8',
      frontFender: '#1a1a1a',
      frameDark: '#135f97',
      basket: '#1c1c1c',
      saddle: '#1b1b1b',
      tire: '#1a1a1a',
      wheelRim: '#ece8df',
      spoke: '#c8cbce',
      hub: '#7a7a7a',
      ring: '#9a9a9a',
      crank: '#9a9a9a',
    },
  },
  chattanooga: {
    basketType: 'rack',
    skirtGuard: {
      type: 'LEVEL_2',
      color: '#a6d50d',
      outerGuard: lyftOuterGuard,
    },
    downTube: 'lyft',
    colors: {
      frame: '#1d5fa0',
      frontFender: '#1d5fa0',
      frameDark: '#154a7a',
      basket: '#1a1a1a',
      saddle: '#1b1b1b',
      tire: '#1a1a1a',
      wheelRim: '#b0b3b6',
      spoke: '#c0c3c6',
      hub: '#7a7a7a',
      ring: '#9a9a9a',
      crank: '#9a9a9a',
    },
  },
  chicago: {
    basketType: 'box',
    skirtGuard: {
      type: 'LEVEL_2',
      color: '#52bfe6',
      outerGuard: lyftOuterGuard,
    },
    downTube: 'lyft',
    colors: {
      frame: '#52bfe6',
      frontFender: '#1a1a1a',
      frameDark: '#2f9cc4',
      basket: '#1c1c1c',
      saddle: '#1b1b1b',
      tire: '#1a1a1a',
      wheelRim: '#ece8df',
      spoke: '#c8cbce',
      hub: '#7a7a7a',
      ring: '#9a9a9a',
      crank: '#9a9a9a',
    },
  },
  columbus: {
    basketType: 'rack',
    skirtGuard: {
      type: 'LEVEL_2',
      color: '#17827c',
      outerGuard: lyftOuterGuard,
    },
    downTube: 'lyft',
    colors: {
      frame: '#17171a',
      frontFender: '#17171a',
      frameDark: '#0b0b0d',
      basket: '#1a1a1a',
      saddle: '#1b1b1b',
      tire: '#1a1a1a',
      wheelRim: '#c4c7ca',
      spoke: '#c8cbce',
      hub: '#8a8a8a',
      ring: '#9a9a9a',
      crank: '#9a9a9a',
    },
  },
  mexico_city: {
    basketType: 'box',
    skirtGuard: {
      type: 'CRESCENT',
      color: '#b8b9bb',
      outerGuard: { endDeg: 150, color: '#1a1a1d' },
    },
    downTube: 'lyft',
    colors: {
      frame: '#1a1a1d',
      frontFender: '#1a1a1d',
      frameDark: '#0c0c0e',
      basket: '#1e1e20',
      saddle: '#1b1b1b',
      tire: '#1a1a1a',
      wheelRim: '#e7e4de',
      spoke: '#c8cbce',
      hub: '#7a7a7a',
      ring: '#2a2a2a',
      crank: '#2a2a2a',
    },
  },
  seoul: {
    basketType: 'wire',
    skirtGuard: { type: 'OUTER_GUARD_150', color: '#1a1a1a' },
    colors: {
      frame: '#f3f3f0',
      frontFender: '#f3f3f0',
      frameDark: '#cfcfc9',
      basket: '#7a7d80',
      saddle: '#1b1b1b',
      tire: '#1a1a1a',
      wheelRim: '#5cbe2d',
      spoke: '#c8cbce',
      hub: '#7a7a7a',
      ring: '#2a2a2a',
      crank: '#2a2a2a',
    },
  },
  taipei: {
    basketType: 'wire',
    skirtGuard: { type: 'CRESCENT', color: '#f7a70a' },
    colors: {
      frame: '#f4f3ef',
      frontFender: '#f7a70a',
      frameDark: '#c9c9c4',
      basket: '#1c1c1c',
      saddle: '#1b1b1b',
      tire: '#1a1a1a',
      wheelRim: '#ece8df',
      spoke: '#c8cbce',
      hub: '#7a7a7a',
      ring: '#f7a70a',
      crank: '#2a2a2a',
    },
  },
  toronto: {
    basketType: 'rack',
    skirtGuard: {
      type: 'LEVEL_1',
      color: '#35a844',
      outerGuard: lyftOuterGuard,
    },
    downTube: 'lyft',
    colors: {
      frame: '#262629',
      frontFender: '#1e1e20',
      frameDark: '#141416',
      basket: '#1e1e20',
      saddle: '#1b1b1b',
      tire: '#1a1a1a',
      wheelRim: '#b8bbbe',
      spoke: '#c8cbce',
      hub: '#7a7a7a',
      ring: '#9a9a9a',
      crank: '#9a9a9a',
    },
  },
  washington_dc: {
    basketType: 'rack',
    skirtGuard: { type: 'OUTER_GUARD_150', color: '#1a1a1a' },
    downTube: 'lyft',
    colors: {
      frame: '#d81f26',
      frontFender: '#1e1e20',
      frameDark: '#a5161c',
      basket: '#1e1e20',
      saddle: '#1b1b1b',
      tire: '#1a1a1a',
      wheelRim: '#b8bbbe',
      spoke: '#c8cbce',
      hub: '#7a7a7a',
      ring: '#9a9a9a',
      crank: '#9a9a9a',
    },
  },
  daejeon: {
    basketType: 'wire',
    skirtGuard: { type: 'OUTER_GUARD_150', color: '#1a1a1a' },
    downTube: 'lyft',
    colors: {
      frame: '#6fb52e',
      frontFender: '#1a1a1a',
      frameDark: '#4e8a1f',
      basket: '#b8bbbe',
      saddle: '#1b1b1b',
      tire: '#1a1a1a',
      wheelRim: '#c4c7ca',
      spoke: '#c8cbce',
      hub: '#7a7a7a',
      ring: '#4e8a1f',
      crank: '#9a9a9a',
    },
  },
  guadalajara: {
    basketType: 'wire',
    skirtGuard: {
      type: 'LEVEL_1',
      color: '#2e8b3d',
      outerGuard: lyftOuterGuard,
    },
    downTube: 'lyft',
    colors: {
      frame: '#bcbfc2',
      frontFender: '#bcbfc2',
      frameDark: '#3aae4a',
      basket: '#1c1c1c',
      saddle: '#1b1b1b',
      tire: '#1a1a1a',
      wheelRim: '#dcdcd8',
      spoke: '#c8cbce',
      hub: '#7a7a7a',
      ring: '#3aae4a',
      crank: '#9a9a9a',
    },
  },
  helsinki: {
    basketType: 'rack',
    skirtGuard: { type: 'FIN', color: '#f5c400', outerGuard: lyftOuterGuard },
    colors: {
      frame: '#f5c400',
      frontFender: '#f5c400',
      frameDark: '#c99a00',
      basket: '#f5c400',
      saddle: '#1b1b1b',
      tire: '#1a1a1a',
      wheelRim: '#c4c7ca',
      spoke: '#c8cbce',
      hub: '#7a7a7a',
      ring: '#9a9a9a',
      crank: '#9a9a9a',
    },
  },
  jersey_city: {
    basketType: 'rack',
    skirtGuard: {
      type: 'LEVEL_2',
      color: '#2f6db5',
      outerGuard: lyftOuterGuard,
    },
    downTube: 'lyft',
    colors: {
      frame: '#2f6db5',
      frontFender: '#2f6db5',
      frameDark: '#235a97',
      basket: '#2a2a2a',
      saddle: '#1b1b1b',
      tire: '#1a1a1a',
      wheelRim: '#bfc2c5',
      spoke: '#c8cbce',
      hub: '#7a7a7a',
      ring: '#2a2a2a',
      crank: '#2a2a2a',
    },
  },
  new_york_city: {
    basketType: 'rack',
    skirtGuard: {
      type: 'LEVEL_2',
      color: '#2f6db5',
      outerGuard: lyftOuterGuard,
    },
    downTube: 'lyft',
    colors: {
      frame: '#2f6db5',
      frontFender: '#2f6db5',
      frameDark: '#235a97',
      basket: '#2a2a2a',
      saddle: '#1b1b1b',
      tire: '#1a1a1a',
      wheelRim: '#bfc2c5',
      spoke: '#c8cbce',
      hub: '#7a7a7a',
      ring: '#2a2a2a',
      crank: '#2a2a2a',
    },
  },
  oslo: {
    basketType: 'rack',
    skirtGuard: { type: '9_1_CIRCLE', color: '#e8e7e3' },
    downTube: 'nordic',
    colors: {
      frame: '#2a7fc0',
      frontFender: '#e8e7e3',
      frameDark: '#1c5f96',
      basket: 'black',
      saddle: '#1b1b1b',
      tire: '#1a1a1a',
      wheelRim: '#c4c7ca',
      spoke: '#c8cbce',
      hub: '#7a7a7a',
      ring: '#2a2a2a',
      crank: '#2a2a2a',
    },
  },
  london: {
    basketType: 'rack',
    skirtGuard: {
      type: 'LEVEL_2',
      color: '#d81f2a',
      outerGuard: lyftOuterGuard,
    },
    downTube: 'lyft',
    colors: {
      frame: '#3f434a',
      frontFender: '#3f434a',
      frameDark: '#2a2d32',
      basket: '#2a2a2a',
      saddle: '#1b1b1b',
      tire: '#1a1a1a',
      wheelRim: '#bfc2c5',
      spoke: '#c8cbce',
      hub: '#7a7a7a',
      ring: '#2a2a2a',
      crank: '#2a2a2a',
    },
  },
  los_angeles: {
    basketType: 'rack',
    skirtGuard: {
      type: '10_3_CIRCLE',
      color: '#a5cd39',
      outerGuard: lyftOuterGuard,
    },
    downTube: 'lyft',
    colors: {
      frame: '#1a1a1a',
      frontFender: '#1a1a1a',
      frameDark: '#0c0c0e',
      basket: '#1a1a1a',
      saddle: '#1b1b1b',
      tire: '#1a1a1a',
      wheelRim: '#bfc2c5',
      spoke: '#c8cbce',
      hub: '#7a7a7a',
      ring: '#2a2a2a',
      crank: '#2a2a2a',
    },
  },
  montreal: {
    basketType: 'rack',
    skirtGuard: {
      type: 'LEVEL_1',
      color: '#d81f2a',
      outerGuard: lyftOuterGuard,
    },
    downTube: 'lyft',
    colors: {
      frame: '#d81f2a',
      frontFender: '#d81f2a',
      frameDark: '#a5161c',
      basket: '#2a2a2a',
      saddle: '#1b1b1b',
      tire: '#1a1a1a',
      wheelRim: '#bfc2c5',
      spoke: '#c8cbce',
      hub: '#7a7a7a',
      ring: '#2a2a2a',
      crank: '#2a2a2a',
    },
  },
  philadelphia: {
    basketType: 'box',
    skirtGuard: {
      type: '10_3_CIRCLE',
      color: '#2277bd',
      outerGuard: lyftOuterGuard,
    },
    downTube: 'lyft',
    colors: {
      frame: '#2277bd',
      frontFender: '#2277bd',
      frameDark: '#185a92',
      basket: '#2277bd',
      saddle: '#1b1b1b',
      tire: '#1a1a1a',
      wheelRim: '#bfc2c5',
      spoke: '#c8cbce',
      hub: '#7a7a7a',
      ring: '#2a2a2a',
      crank: '#2a2a2a',
    },
  },
  pittsburgh: {
    basketType: 'rack',
    skirtGuard: {
      type: 'LEVEL_1',
      color: '#1f4c9c',
      outerGuard: lyftOuterGuard,
    },
    downTube: 'lyft',

    colors: {
      frame: '#1f4c9c',
      frontFender: '#1a1a1a',
      frameDark: '#14336b',
      basket: '#2a2a2a',
      saddle: '#1b1b1b',
      tire: '#1a1a1a',
      wheelRim: '#e7e4dd',
      spoke: '#c8cbce',
      hub: '#7a7a7a',
      ring: '#2a2a2a',
      crank: '#2a2a2a',
    },
  },
  rosario: {
    basketType: 'wire',
    skirtGuard: {
      type: '10_3_CIRCLE',
      color: '#e8e7e3',
      outerGuard: { color: '#4aae3f', endDeg: 150 },
    },
    colors: {
      frame: '#4aae3f',
      frontFender: '#4aae3f',
      frameDark: '#2f7d28',
      basket: '#1c1c1c',
      saddle: '#1b1b1b',
      tire: '#1a1a1a',
      wheelRim: '#c4c7ca',
      spoke: '#c8cbce',
      hub: '#7a7a7a',
      ring: '#2f7d28',
      crank: '#9a9a9a',
    },
  },
  san_francisco: {
    basketType: 'box',
    skirtGuard: { type: '10_3_CIRCLE', color: '#b565a7' },
    downTube: 'lyft',
    colors: {
      frame: '#bcbfc2',
      frontFender: '#bcbfc2',
      frameDark: '#8a8d90',
      basket: '#bcbfc2',
      saddle: '#1b1b1b',
      tire: '#1a1a1a',
      wheelRim: '#ece8df',
      spoke: '#c8cbce',
      hub: '#7a7a7a',
      ring: '#2a2a2a',
      crank: '#2a2a2a',
    },
  },
  trondheim: {
    basketType: 'rack',
    skirtGuard: {
      type: '9_1_CIRCLE',
      color: '#e8e7e3',
      outerGuard: {
        endDeg: 180,
        color: '#d13b2e',
      },
    },
    downTube: 'nordic',
    colors: {
      frame: '#e8e7e3',
      frontFender: '#e8e7e3',
      frameDark: '#c7c7c2',
      basket: '#d13b2e',
      saddle: '#1b1b1b',
      tire: '#1a1a1a',
      wheelRim: '#d13b2e',
      spoke: '#c8cbce',
      hub: '#7a7a7a',
      ring: '#2a2a2a',
      crank: '#2a2a2a',
    },
  },
  vancouver: {
    basketType: 'box',
    skirtGuard: {
      type: 'CRESCENT',
      color: '#e0342a',
      outerGuard: lyftOuterGuard,
    },
    colors: {
      frame: '#c4c4c4',
      frontFender: '#c4c4c4',
      frameDark: '#9a9a9a',
      basket: '#e0342a',
      saddle: '#1b1b1b',
      tire: '#1a1a1a',
      wheelRim: '#b8bbbe',
      spoke: '#c8cbce',
      hub: '#7a7a7a',
      ring: '#9a9a9a',
      crank: '#9a9a9a',
    },
  },
}

/** City ids that have a bike config, in display order. */
export const CONFIGURED_CITY_IDS = Object.keys(CITY_BIKE_CONFIG)
